[package]
name = "crate-race"
version = "0.5.0"
authors = ["Veniamin Ilmer"]
edition = "2018"

[dependencies]
bencher = "*"
regex = "*"

#json
json = "*"
serde_json = "*"
json5 = "*"
json_in_type = "*"

#big_nums
num-bigint = "*"
num-traits = "*"  #Used by bigint code
uint = "*"
numext-fixed-uint = "*"

#md5
md5 = "*"
md_5 = { version = "*", package = "md-5" }

#csv
csv = "*"
quick-csv = "*"
simple-csv = "*"

[[bench]]
name = "big_arithmetic"
path = "benches/big_arithmetic/bench.rs"
harness = false

[[bench]]
name = "csv_parse"
path = "benches/csv_parse/bench.rs"
harness = false

[[bench]]
name = "json_build"
path = "benches/json_build/bench.rs"
harness = false

[[bench]]
name = "json_parse"
path = "benches/json_parse/bench.rs"
harness = false

[[bench]]
name = "md5"
path = "benches/md5/bench.rs"
harness = false
