[package]
name = "crate-race"
version = "0.2.0"
authors = ["Veniamin Ilmer"]
edition = "2018"

[dependencies]
bencher = "*"
regex = "*"

#json_parse
json = "*"
serde_json = "*"
json5 = "*"

json_in_type = "*"

#big_arithmetic
num-bigint = "*"
num-traits = "*"  #Used by bigint code
uint = "*"

[[bench]]
name = "json_parse"
path = "benches/json_parse/bench.rs"
harness = false

[[bench]]
name = "big_arithmetic"
path = "benches/big_arithmetic/bench.rs"
harness = false
